# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4da45205f00f71ca6e7affe80a3d773eecd1ac4b2d7bd87fe2f7b5dd5ca566dd58655afbc42a661858340e225590878eb51618c0fa7f64b77698b43afaea2efc

test:
  secret_key_base: 7ed8864a8f4f2fbb9e136665585d2a91add97fb697e05fe075c3835a5319a549387c8ebf5814b695c1cc6cc831594f4a66bad9a91b30802e541496b947a6ce3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
